wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_1.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_2.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_3.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_4.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_5.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_6.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_7.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_8.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_9.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_10.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_11.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_12.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_13.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_14.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_15.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_16.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_17.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_18.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_20.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_21.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_22.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_23.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_24.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_25.zip
wget https://aerialvln.s3.ap-southeast-2.amazonaws.com/simulator/env_26.zip
